### PR TITLE
Upgrade to Angular 8

### PR DESCRIPTION
**Pull request by frankie567**
### Context

Following #156, here is an update to support Angular 8.

### How has this been tested?

Existing unit tests pass.

### Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature or improvement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Basically, I applied the [Angular 8 update procedure](https://update.angular.io/#7.0:8.0).

I'm not 100% sure that it'll break installations using previous versions of Angular. I've tried on my own Angular 7 project, and it works properly.

Notice there is a change of lifecycle hook (from `ngAfterContentInit` to `ngAfterViewInit`) in order to comply with new resolution strategy for `@ViewChild` that'll become the default in Angular 9. Full rationale about this here: https://angular.io/guide/static-query-migration

### Related issue(s):

1. #156 

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
@wojciechczerniak @swistach will we be able to update now?

**Comment by wojciechczerniak** [comment]
That will help a lot. But we have to check if those changes are backward compatible.

**Comment by frankie567** [comment]
@wojciechczerniak Tell me if I can do something to help further 👍

**Comment by frankie567** [comment]
Thank you for your feedback @swistach! Yes, you're right it should be `New feature or improvement`, it's just that I didn't want to be over-confident about those changes :)

**Comment by swistach** [comment]
Alright, then we can mark it as an improvement :)
I merged your PR into `develop`. I guess we will release `@handsontable/angular@5.1.0` next week.
Stay tuned and thank you!

**Comment by frankie567** [comment]
That's great news 🎉Thanks!

**Pull request merged**
