### PR TITLE
Add Codesandbox CI configuration file

### PR DESCRIPTION
**Pull request by wojciechczerniak**
### Context

This will build an example for each PR and add additional ones if they are a part of the Issue or PR description.

### How has this been tested?

If the PR has a build attached, then it works.

### Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature or improvement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1.
2.
3.

### Checklist:

- [ ] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
@jansiegel As you're now gaining the expertise on Angular wrapper, can you review my PR? 😄

**Comment by jansiegel** [comment]
@wojciechczerniak Are the changes in `package.json` and `package-lock.json` needed?

**Comment by aninde** [comment]
I got this issue and yet I see that the questions have not been answered here. https://github.com/handsontable/angular-handsontable/pull/200#issuecomment-665621251 @wojciechczerniak

**Comment by wojciechczerniak** [comment]
This should be configured for monorepo, not here

**Pull request closed without merging**
